xtd::Application
argument
mandatory argument for option
requirement
option is optional on command line
typedef std::function<void(void)> xtd::Application::t_sig_handler
Signal handler functor prototype,.
addSignalHandler
typedef std::function<void(const string&, const t_option&)> xtd::Application::t_callback
typedef vector<t_option> xtd::Application::t_option_list
friend class ::TestApplication
string xtd::Application::m_binName
binary name (argv[0])
Referenced by execute, isOptionGiven.
uint32_t xtd::Application::m_logLevel
log level read from command line
Referenced by Application, execute.
vector<string> xtd::Application::m_remainingArgs
positional command line arguments
Referenced by addOption.
string xtd::Application::m_rcsid
binary identity information
Referenced by getVersion.
bool xtd::Application::m_disableExit
holds exit activation state
Referenced by isOptionGiven.
bool xtd::Application::m_disableCatch
holds exception catching state
Referenced by execute.
t_option_list xtd::Application::m_optionList
string xtd::Application::m_helpText
boost::thread xtd::Application::m_runThread
boost::asio::io_service xtd::Application::m_ioService
boost::asio::io_service::work xtd::Application::m_work
boost::asio::signal_set xtd::Application::m_signals
map<int, t_sig_handler> xtd::Application::m_signalHandlerMap
xtd::Application::Application(bool p_disableExit=false, bool p_disableCatch=false)
Constructor.
p_disableExit If true, throws exception instead of exiting on error p_disableCatch If true, exception are not caught at top level std::runtime_error
References addOption, none, optional, bindCallback, mandatory, bindValues, m_logLevel.
xtd::Application::~Application(void)
Destructor.
int xtd::Application::execute(int p_argc, const char *const p_argv[])
main entry point, usually called with main(int,char**)'s arguments
p_argc argument count p_argv argument list (first is binary name) depends on Application::process implementation, usually 0 if process succeed
References m_binName, error_nohelp, xtd::log::getRoot, xtd::log::RootLogger::initialize, xtd::log::crit, parseConfig, checkOptions, xtd::log::RootLogger::setAllLevels, xtd::log::from, m_logLevel, initialize, process, m_disableCatch, HERE.
virtual void xtd::Application::parseConfig(void)
Parse application configuration, (default nothing)
Referenced by execute.
virtual void xtd::Application::checkOptions(void)
Check read options, (default nothing)
Referenced by execute.
virtual void xtd::Application::initialize(void)
initialize application, (default nothing)
References process, addSignalHandler, getVersion, addOption, isOptionGiven, addHelpMsg, bindDir, bindFile, bindGiven, bindString, bindRegex, bindCallback, bindValueIfGiven, bindNumber, bindValues, bindAccumulator, error_nohelp, error, warn.
Referenced by execute.
int xtd::Application::process(void)
Main application process function, (default nothing)
Up to the user, generally 0 in case of success
Referenced by execute, initialize.
bool xtd::Application::addSignalHandler(int p_signalNumber, t_sig_handler p_handler)
register a signal callback
p_signalNumber signal ID (man signal 7) p_handler handling callback True if signal registered correctly, false if signal was already registered
Referenced by initialize.
const string & xtd::Application::getVersion(void) const
Get RCSID identity informations.
References m_rcsid.
Referenced by initialize.
void xtd::Application::addOption(const char p_shortOpt, const string &p_longOpt, const argument p_argType, const requirement p_status, const string &p_description, t_callback p_callback)
Register an option to parser.
p_shortOpt short form, single character p_longOpt long form, not starting with dash p_argType shall we expect an argument p_status should the option be given by user p_description usage help description p_callback functor to call when option is encountered Option must : a unique short forma unique long formshort and long forms must not start by a dash (-) Programs logs and exit in case of error.
References error, none, mandatory, optional, m_remainingArgs.
Referenced by Application, initialize.
bool xtd::Application::isOptionGiven(const string &p_optionName) const
Tells if given option was given on command line.
p_optionName long-form or short-form of the option true if option was given
References m_binName, none, mandatory, m_disableExit.
Referenced by initialize.
void xtd::Application::addHelpMsg(const string &p_helpMessage)
Add additional usage line to display on help or errors.
p_helpMessage Message line to add
Referenced by initialize.
Application::t_callback xtd::Application::bindDir(string &p_target) const
Bind option's parameter to a directory.
p_target Reference variable to store the option's value generated option callback
References error.
Referenced by initialize.
Application::t_callback xtd::Application::bindFile(string &p_target, bool p_readable=true) const
Bind option's parameter to a file name.
p_target Reference variable to store the option's value p_readable If true, check that given file name exists and is readable generated option callback
References error.
Referenced by initialize.
Application::t_callback xtd::Application::bindGiven(bool &p_target) const
Set targeted variable to true if option is given on command line.
p_target Reference variable generated option callback
Referenced by initialize.
Application::t_callback xtd::Application::bindString(string &p_target) const
Set targeted variable to option's parameter.
p_target Reference variable generated option callback
Referenced by initialize.
Application::t_callback xtd::Application::bindRegex(string &p_target) const
Set targeted variable to option's parameter regex.
p_target Reference variable generated option callback
References error.
Referenced by initialize.
t_callback xtd::Application::bindCallback(T p_action) const
Associate option to given generic callback.
p_action function compatible withstd::function<void(void)> signature generated option callback
Referenced by Application, initialize.
t_callback xtd::Application::bindValueIfGiven(T &p_target, const T &p_value) const
Set given value to referenced variable if option is given.
p_target Reference variable p_value Value to set to p_target generated option callback
Referenced by initialize.
t_callback xtd::Application::bindNumber(T &p_target, T p_min=std::numeric_limits< T >::min(), T p_max=std::numeric_limits< T >::max()) const
Bind option's paramter as number to referenced variable.
p_target Reference variable p_min Minimum parameter value [inclusive] p_max Maximum parameter value [inclusive] generated option callback Will led to an error if input parameter : not lexically convertible to Tis lower than p_minis greater than p_max
Referenced by initialize.
t_callback xtd::Application::bindValues(T &p_target, const Iterable &p_values) const
Bind option's parameter to target variable and checks among authorized values.
p_target Reference variable p_values Iterable container of authorized option's values generated option callback
Referenced by Application, initialize.
t_callback xtd::Application::bindAccumulator(TCollection &p_target) const
Append option's parameter to target container for each command line hit.
p_target Reference variable container generated option callback
Referenced by initialize.
void xtd::Application::error_nohelp(int p_code, const string &p_format, Arguments &&...p_args) const
Prints error on standard error and exit.
p_code exit code p_format error message format (boost::format compatible) p_args Template variadic arguments to format
Referenced by execute, initialize.
void xtd::Application::error(int p_code, const string &p_format, Arguments &&...p_args) const
Prints error and usage on standard error and exit.
p_code exit code p_format error message format (boost::format compatible) p_args Template variadic arguments to format
Referenced by bindFile, bindDir, bindRegex, addOption, initialize.
void xtd::Application::warn(const string &p_format, Arguments &&...p_args) const
Prints a warning on standard error.
p_format error message format (boost::format compatible) p_args Template variadic arguments to format
Referenced by initialize.
void xtd::Application::readArgs(int p_argc, const char *const p_argv[])
Reset getopt_long internal global variable.
void xtd::Application::usage(std::ostream &p_stream=std::cerr) const
void xtd::Application::handleSignal(const boost::system::error_code &p_error, int p_signalNumber)
Mysteriously appeared here. Commented until any bug pops back.